name: Hourly Sales Scan

on:
  schedule:
    # Run every hour at minute 0 (UTC)
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Sales Scan
        run: |
          curl -X POST "${{ secrets.VERCEL_URL }}/api/scan" \
            -H "Content-Type: application/json" \
            --max-time 300 \
            --retry 2